# Basic formatting - using only stable rustfmt features
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Arrays and alignment
array_width = 90
fn_call_width = 60

# Match expressions
match_block_trailing_comma = true

# Imports (stable features only)
reorder_imports = true
reorder_modules = true

# Other stable preferences
use_field_init_shorthand = true
use_try_shorthand = true

# Struct formatting (stable features only)
struct_lit_width = 50
struct_variant_width = 50

# Chain formatting
chain_width = 50
single_line_if_else_max_width = 80
